from __future__ import annotations


LANGUAGE_DISPLAY_MAP: dict[str, str] = {
    "pol": "Polski",
    "pl": "Polski",
    "eng": "Angielski",
    "en": "Angielski",
    "deu": "Niemiecki",
    "ger": "Niemiecki",
    "de": "Niemiecki",
    "abk": "Abchaski",
    "ab": "Abchaski",
    "afr": "Afrykanerski",
    "af": "Afrykanerski",
    "alb": "Albański",
    "sqi": "Albański",
    "sq": "Albański",
    "amh": "Amharski",
    "am": "Amharski",
    "ara": "Arabski",
    "ar": "Arabski",
    "arg": "Aragoński",
    "an": "Aragoński",
    "arm": "Ormiański",
    "hye": "Ormiański",
    "hy": "Ormiański",
    "asm": "Asamski",
    "as": "Asamski",
    "ava": "Awarski",
    "av": "Awarski",
    "ave": "Awestyjski",
    "ae": "Awestyjski",
    "aym": "Ajmara",
    "ay": "Ajmara",
    "aze": "Azerski",
    "az": "Azerski",
    "bak": "Baszkirski",
    "ba": "Baszkirski",
    "bos": "Bośniacki",
    "bs": "Bośniacki",
    "bre": "Bretoński",
    "br": "Bretoński",
    "bul": "Bułgarski",
    "bg": "Bułgarski",
    "cat": "Kataloński",
    "ca": "Kataloński",
    "chi": "Chiński",
    "zho": "Chiński",
    "zh": "Chiński",
    "fra": "Francuski",
    "fre": "Francuski",
    "fr": "Francuski",
    "hrv": "Chorwacki",
    "hr": "Chorwacki",
    "dan": "Duński",
    "da": "Duński",
    "div": "Malediwski",
    "dv": "Malediwski",
    "spa": "Hiszpański",
    "es": "Hiszpański",
    "ita": "Włoski",
    "it": "Włoski",
    "ukr": "Ukraiński",
    "uk": "Ukraiński",
    "rus": "Rosyjski",
    "ru": "Rosyjski",
    "ces": "Czeski",
    "cze": "Czeski",
    "cs": "Czeski",
    "slk": "Słowacki",
    "slo": "Słowacki",
    "sk": "Słowacki",
    "lit": "Litewski",
    "lt": "Litewski",
    "bel": "Białoruski",
    "be": "Białoruski",
    "lat": "Łaciński",
    "la": "Łaciński",
    "dzo": "Dzongkha",
    "dz": "Dzongkha",
    "epo": "Esperanto",
    "eo": "Esperanto",
    "est": "Estoński",
    "et": "Estoński",
    "fao": "Farerski",
    "fo": "Farerski",
    "fij": "Fidżyjski",
    "fj": "Fidżyjski",
    "fin": "Fiński",
    "fi": "Fiński",
    "fry": "Zachodniofryzyjski",
    "fy": "Zachodniofryzyjski",
    "gla": "Szkocki gaelicki",
    "gd": "Szkocki gaelicki",
    "gle": "Irlandzki",
    "ga": "Irlandzki",
    "glg": "Galicyjski",
    "gl": "Galicyjski",
    "grc": "Greka starożytna",
    "gre": "Grecki",
    "ell": "Grecki",
    "el": "Grecki",
    "guj": "Gudźarati",
    "gu": "Gudźarati",
    "hat": "Haitański",
    "ht": "Haitański",
    "hau": "Hausa",
    "ha": "Hausa",
    "heb": "Hebrajski",
    "he": "Hebrajski",
    "her": "Herero",
    "hz": "Herero",
    "hin": "Hindi",
    "hi": "Hindi",
    "hmo": "Hiri motu",
    "ho": "Hiri motu",
    "hun": "Węgierski",
    "hu": "Węgierski",
    "ibo": "Igbo",
    "ig": "Igbo",
    "ice": "Islandzki",
    "isl": "Islandzki",
    "is": "Islandzki",
    "ido": "Ido",
    "io": "Ido",
    "ind": "Indonezyjski",
    "id": "Indonezyjski",
    "ina": "Interlingua",
    "ia": "Interlingua",
    "ile": "Interlingue",
    "ie": "Interlingue",
    "ipk": "Inupiak",
    "ik": "Inupiak",
    "jpn": "Japoński",
    "ja": "Japoński",
    "jav": "Jawajski",
    "jv": "Jawajski",
    "geo": "Gruziński",
    "kat": "Gruziński",
    "ka": "Gruziński",
    "kal": "Grenlandzki",
    "kl": "Grenlandzki",
    "kan": "Kannada",
    "kn": "Kannada",
    "kas": "Kaszmirski",
    "ks": "Kaszmirski",
    "kaz": "Kazachski",
    "kk": "Kazachski",
    "khm": "Khmerski",
    "km": "Khmerski",
    "kik": "Kikuju",
    "ki": "Kikuju",
    "kin": "Rwanda",
    "rw": "Rwanda",
    "kir": "Kirgiski",
    "ky": "Kirgiski",
    "kom": "Komi",
    "kv": "Komi",
    "kon": "Kongo",
    "kg": "Kongo",
    "kor": "Koreański",
    "ko": "Koreański",
    "kua": "Kuanyama",
    "kj": "Kuanyama",
    "kur": "Kurdyjski",
    "ku": "Kurdyjski",
    "lao": "Laotański",
    "lo": "Laotański",
    "lav": "Łotewski",
    "lv": "Łotewski",
    "lim": "Limburski",
    "li": "Limburski",
    "lin": "Lingala",
    "ln": "Lingala",
    "ltz": "Luksemburski",
    "lb": "Luksemburski",
    "lug": "Ganda",
    "lg": "Ganda",
    "mac": "Macedoński",
    "mkd": "Macedoński",
    "mk": "Macedoński",
    "mah": "Marshallski",
    "mh": "Marshallski",
    "mal": "Malajalam",
    "ml": "Malajalam",
    "mao": "Maoryski",
    "mri": "Maoryski",
    "mi": "Maoryski",
    "mar": "Marathi",
    "mr": "Marathi",
    "may": "Malajski",
    "msa": "Malajski",
    "ms": "Malajski",
    "mlg": "Malgaski",
    "mg": "Malgaski",
    "mlt": "Maltański",
    "mt": "Maltański",
    "mon": "Mongolski",
    "mn": "Mongolski",
    "nau": "Nauru",
    "na": "Nauru",
    "nav": "Nawaho",
    "nv": "Nawaho",
    "nbl": "Ndebele południowy",
    "nr": "Ndebele południowy",
    "nde": "Ndebele północny",
    "nd": "Ndebele północny",
    "ndo": "Ndonga",
    "ng": "Ndonga",
    "nep": "Nepalski",
    "ne": "Nepalski",
    "dut": "Niderlandzki",
    "nld": "Niderlandzki",
    "nl": "Niderlandzki",
    "nno": "Norweski nynorsk",
    "nn": "Norweski nynorsk",
    "nob": "Norweski bokmal",
    "nb": "Norweski bokmal",
    "nor": "Norweski",
    "no": "Norweski",
    "nya": "Njandża",
    "ny": "Njandża",
    "oci": "Oksytański",
    "oc": "Oksytański",
    "oji": "Odżibwe",
    "oj": "Odżibwe",
    "ori": "Orija",
    "or": "Orija",
    "orm": "Oromo",
    "om": "Oromo",
    "oss": "Osetyjski",
    "os": "Osetyjski",
    "pan": "Pendżabski",
    "pa": "Pendżabski",
    "per": "Perski",
    "fas": "Perski",
    "fa": "Perski",
    "pli": "Pali",
    "pi": "Pali",
    "por": "Portugalski",
    "pt": "Portugalski",
    "pus": "Paszto",
    "ps": "Paszto",
    "que": "Keczua",
    "qu": "Keczua",
    "roh": "Retoromański",
    "rm": "Retoromański",
    "rum": "Rumuński",
    "ron": "Rumuński",
    "ro": "Rumuński",
    "sag": "Sango",
    "sg": "Sango",
    "san": "Sanskryt",
    "sa": "Sanskryt",
    "sin": "Syngaleski",
    "si": "Syngaleski",
    "slv": "Słoweński",
    "sl": "Słoweński",
    "sme": "Północnolapoński",
    "se": "Północnolapoński",
    "smo": "Samoański",
    "sm": "Samoański",
    "sna": "Shona",
    "sn": "Shona",
    "som": "Somalijski",
    "so": "Somalijski",
    "sot": "Sotho południowy",
    "st": "Sotho południowy",
    "srp": "Serbski",
    "sr": "Serbski",
    "sun": "Sundajski",
    "su": "Sundajski",
    "swa": "Suahili",
    "sw": "Suahili",
    "ssw": "Suazi",
    "ss": "Suazi",
    "swe": "Szwedzki",
    "sv": "Szwedzki",
    "tah": "Tahitański",
    "ty": "Tahitański",
    "tam": "Tamilski",
    "ta": "Tamilski",
    "tat": "Tatarski",
    "tt": "Tatarski",
    "tel": "Telugu",
    "te": "Telugu",
    "tgk": "Tadżycki",
    "tg": "Tadżycki",
    "tgl": "Tagalski",
    "tl": "Tagalski",
    "tha": "Tajski",
    "th": "Tajski",
    "tib": "Tybetański",
    "bod": "Tybetański",
    "bo": "Tybetański",
    "tir": "Tigrinia",
    "ti": "Tigrinia",
    "ton": "Tonga",
    "to": "Tonga",
    "tsn": "Tswana",
    "tn": "Tswana",
    "tso": "Tsonga",
    "ts": "Tsonga",
    "tuk": "Turkmeński",
    "tk": "Turkmeński",
    "tur": "Turecki",
    "tr": "Turecki",
    "twi": "Twi",
    "tw": "Twi",
    "uig": "Ujgurski",
    "ug": "Ujgurski",
    "urd": "Urdu",
    "ur": "Urdu",
    "uzb": "Uzbecki",
    "uz": "Uzbecki",
    "ven": "Venda",
    "ve": "Venda",
    "vie": "Wietnamski",
    "vi": "Wietnamski",
    "vol": "Volapuk",
    "vo": "Volapuk",
    "wel": "Walijski",
    "cym": "Walijski",
    "cy": "Walijski",
    "wln": "Waloński",
    "wa": "Waloński",
    "wol": "Wolof",
    "wo": "Wolof",
    "xho": "Xhosa",
    "xh": "Xhosa",
    "yid": "Jidysz",
    "yi": "Jidysz",
    "yor": "Joruba",
    "yo": "Joruba",
    "zha": "Zhuang",
    "za": "Zhuang",
    "zul": "Zulu",
    "zu": "Zulu",
}


def normalize_language_code(value: str | None) -> str | None:
    if value is None:
        return None
    normalized = value.strip().lower()
    return normalized or None


def get_language_display(value: str | None) -> str | None:
    normalized = normalize_language_code(value)
    if normalized is None:
        return None
    return LANGUAGE_DISPLAY_MAP.get(normalized, normalized.upper())


# Mapping from ISO 639-1 (2-letter) to the ISO 639-3 code stored in the database.
_ISO_639_1_TO_639_3: dict[str, str] = {
    "pl": "pol", "en": "eng", "de": "ger", "fr": "fre", "es": "spa",
    "it": "ita", "ru": "rus", "uk": "ukr", "cs": "ces", "sk": "slk",
    "be": "bel", "la": "lat", "ar": "ara", "zh": "chi", "ja": "jpn",
    "ko": "kor", "pt": "por", "nl": "nld", "sv": "swe", "no": "nor",
    "da": "dan", "fi": "fin", "hu": "hun", "ro": "rum", "bg": "bul",
    "hr": "hrv", "sr": "srp", "sl": "slv", "lt": "lit", "lv": "lav",
    "et": "est", "el": "ell", "tr": "tur", "he": "heb", "vi": "vie",
    "th": "tha", "id": "ind", "ms": "may", "fa": "per", "ka": "geo",
    "af": "afr", "sq": "alb", "hy": "arm", "az": "aze", "bs": "bos",
    "ca": "cat", "eu": "baq", "bn": "ben", "my": "bur",
}


def normalize_language_to_iso3(code: str | None) -> str | None:
    """Convert an ISO 639-1 two-letter code to ISO 639-3 used in the database.

    The library catalogue stores language codes in ISO 639-3 (three-letter) format.
    The LLM and the API accept ISO 639-1 (two-letter) codes. This function
    normalises the code before it is used in database queries.

    Args:
        code: A language code in ISO 639-1 or ISO 639-3 format, or None.

    Returns:
        The ISO 639-3 equivalent, or the original code if it is already 3+ letters.
        Returns None when ``code`` is None or empty.
    """
    if not code:
        return None
    normalized = code.strip().lower()
    if len(normalized) == 2:
        return _ISO_639_1_TO_639_3.get(normalized, normalized)
    return normalized