# Generated by Django 6.0.1 on 2026-03-09 18:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ISBN')),
                ('integration_source', models.SmallIntegerField(default=0, verbose_name='Integration Source')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('data_source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Data Source')),
                ('google_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Google Books ID')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Publisher')),
                ('publication_date', models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True, verbose_name='Publication Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Page Count')),
                ('print_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Print Type')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category')),
                ('cover_url', models.URLField(blank=True, null=True, verbose_name='Cover URL')),
                ('language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Libraries',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Role ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Role Name')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Status Name')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Library User',
                'verbose_name_plural': 'Library Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.book')),
            ],
            options={
                'verbose_name': 'Book Author',
                'verbose_name_plural': 'Book Authors',
                'unique_together': {('author', 'book')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='domain.BookAuthor', to='domain.author', verbose_name='Authors'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Reservation Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Reservation End Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.book', verbose_name='Book')),
                ('librarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_as_librarian', to=settings.AUTH_USER_MODEL, verbose_name='Librarian')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.library', verbose_name='Library')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_as_reader', to=settings.AUTH_USER_MODEL, verbose_name='Reader')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.book')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.library')),
            ],
            options={
                'verbose_name': 'Book in Library',
                'verbose_name_plural': 'Books in Libraries',
                'unique_together': {('book', 'library')},
            },
        ),
        migrations.CreateModel(
            name='LibraryAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.library')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.role')),
            ],
            options={
                'verbose_name': 'Library Administrator',
                'verbose_name_plural': 'Library Administrators',
                'unique_together': {('library', 'user')},
            },
        ),
    ]
