# Generated by Django 6.0.1 on 2026-02-26 21:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa oddziału')),
                ('street', models.TextField(verbose_name='Ulica')),
                ('city', models.CharField(max_length=255, verbose_name='Miasto')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Kod pocztowy')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Dodatkowe informacje')),
            ],
            options={
                'verbose_name': 'Oddział biblioteki',
                'verbose_name_plural': 'Oddziały biblioteki',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa biblioteki')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis biblioteki')),
            ],
            options={
                'verbose_name': 'Biblioteka',
                'verbose_name_plural': 'Biblioteki',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Użytkownik',
                'verbose_name_plural': 'Użytkownicy',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil administratora',
                'verbose_name_plural': 'Profile administratorów',
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=32, verbose_name='ISBN')),
                ('year', models.PositiveIntegerField(verbose_name='Rok wydania')),
                ('publisher', models.CharField(max_length=255, verbose_name='Wydawnictwo')),
                ('total_copies', models.PositiveIntegerField(verbose_name='Liczba egzemplarzy')),
                ('available_copies', models.PositiveIntegerField(verbose_name='Dostępne egzemplarze')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Dodatkowe informacje')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='domain.book', verbose_name='Książka')),
            ],
            options={
                'verbose_name': 'Edycja książki',
                'verbose_name_plural': 'Edycje książek',
            },
        ),
        migrations.CreateModel(
            name='LibrarianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='librarian_profile', to=settings.AUTH_USER_MODEL)),
                ('libraries', models.ManyToManyField(related_name='librarians', to='domain.library', verbose_name='Biblioteki')),
            ],
            options={
                'verbose_name': 'Profil bibliotekarza',
                'verbose_name_plural': 'Profile bibliotekarzy',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('expires_at', models.DateTimeField(verbose_name='Data wygaśnięcia')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='domain.edition', verbose_name='Edycja książki')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
            },
        ),
        migrations.CreateModel(
            name='UKDCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('nazwa_dzialu', models.CharField(max_length=255, verbose_name='Nazwa działu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='domain.ukdcategory', verbose_name='Kategoria nadrzędna')),
            ],
            options={
                'verbose_name': 'Kategoria UKD',
                'verbose_name_plural': 'Kategorie UKD',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='ukd_categories',
            field=models.ManyToManyField(related_name='books', to='domain.ukdcategory', verbose_name='Kategorie UKD'),
        ),
    ]
