# Generated by Django 6.0.1 on 2026-03-13 16:39

from django.db import migrations, models

# Manually created to fix the migration error
# It is not a good practice to modify migrations that have been already applied to the database
# but in this case, it is the easiest way to fix the problem
def forwards_func(apps, schema_editor):
    Library = apps.get_model('domain', 'Library')
    LibraryUser = apps.get_model('domain', 'LibraryUser')
    db_alias = schema_editor.connection.alias

    Library.objects.using(db_alias).all().delete()
    LibraryUser.objects.using(db_alias).all().delete()

def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_alter_book_isbn_alter_role_id'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
        migrations.AlterField(
            model_name='library',
            name='region',
            field=models.IntegerField(blank=True, choices=[(1, 'dolnośląskie'), (2, 'kujawsko-pomorskie'), (3, 'lubelskie'), (4, 'lubuskie'), (5, 'łódzkie'), (6, 'małopolskie'), (7, 'mazowieckie'), (8, 'opolskie'), (9, 'podkarpackie'), (10, 'podlaskie'), (11, 'pomorskie'), (12, 'śląskie'), (13, 'świętokrzyskie'), (14, 'warmińsko-mazurskie'), (15, 'wielkopolskie'), (16, 'zachodniopomorskie')], null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='libraryuser',
            name='region',
            field=models.IntegerField(blank=True, choices=[(1, 'dolnośląskie'), (2, 'kujawsko-pomorskie'), (3, 'lubelskie'), (4, 'lubuskie'), (5, 'łódzkie'), (6, 'małopolskie'), (7, 'mazowieckie'), (8, 'opolskie'), (9, 'podkarpackie'), (10, 'podlaskie'), (11, 'pomorskie'), (12, 'śląskie'), (13, 'świętokrzyskie'), (14, 'warmińsko-mazurskie'), (15, 'wielkopolskie'), (16, 'zachodniopomorskie')], null=True, verbose_name='Region'),
        ),
    ]
