# Generated by Django 6.0.3 on 2026-05-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0018_mailnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailnotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
